version: '3'
services:
  reactfront:
    build:
      context: .
    image: superheatedboy/reactfront:latest
    ports:
      - "3000:3000"
    tty: true # コンテナが正常終了するのを防ぐ

  customersapi:
    build:
      context: ./customers
    image: superheatedboy/customersapi:latest
    ports:
      - "3002:3002"
      
  reviewsapi:
    build:
      context: ./reviews
    image: superheatedboy/reviewsapi:latest
    ports:
      - "3003:3003"

  historiesapi:
    build:
      context: ./histories
    image: superheatedboy/historiesapi:latest
    ports:
      - "3005:3005"
      
  nginx:
    depends_on:
      - customers
      - reviews
      - histories
      - reactfront
    restart: always
    build:
      context: ./nginxrp
    ports:
      - "3050:80"

# docker-compose up --build
# docker-compose exec reactbookfront sh
# docker-compose exec reactbookfront curl http://productsapi:3001/api/products
