version: '3'
services:
  reactfront:
    build:
      context: ./reactfront
    image: superheatedboy/reactfront:latest
    ports:
      - "3000:3000"
    tty: true # コンテナが正常終了するのを防ぐ

  customers:
    build:
      context: ./customers
    image: superheatedboy/customers:latest
    ports:
      - "3002:3002"
      
  reviews:
    build:
      context: ./reviews
    image: superheatedboy/reviews:latest
    ports:
      - "3003:3003"

  histories:
    build:
      context: ./histories
    image: superheatedboy/histories:latest
    ports:
      - "3005:3005"
      
  nginx:
    depends_on:
      - customers
      - reviews
      - histories
      - reactfront
    restart: always
    build:
      context: ./nginxrp
    ports:
      - "3050:80"

# docker-compose up --build
# docker-compose exec reactfront sh
# docker-compose exec reactfront curl http://productsapi:3001/api/products
