version: '3'
services:
  reactbookfront:
    build:
      context: .
    image: superheatedboy/reactbookfront:latest
    ports:
      - "3000:3000"
    tty: true # コンテナが正常終了するのを防ぐ

  productsapi:
    build:
      context: ./productscarts
    image: superheatedboy/productsapi:latest
    ports:
      - "3001:3001"

  tokenapi:
    build:
      context: ./auth-tutorial
    image: superheatedboy/tokenapi:latest
    ports:
      - "3002:3002"
      
  reviewsapi:
    build:
      context: ./reviews
    image: superheatedboy/reviewsapi:latest
    ports:
      - "3003:3003"
      
  nginx:
    depends_on:
      - productsapi
      - reactbookfront
    restart: always
    build:
      context: ./nginxrp
    ports:
      - "3050:80"

# docker-compose up --build
# docker-compose exec reactbookfront sh
# docker-compose exec reactbookfront curl http://productsapi:3001/api/products
