version: '3'
services:
  reactfront:
    build:
      context: ./reactfront
    image: superheatedboy/reactfront:latest
    ports:
      - "3000:3000"
    tty: true # コンテナが正常終了するのを防ぐ

  customers:
    build:
      context: ./customers
    image: superheatedboy/customers:latest
    ports:
      - "3002:3002"
      
  reviews:
    build:
      context: ./reviews
    image: superheatedboy/reviews:latest
    ports:
      - "3003:3003"

  histories:
    depends_on:
      - histories-redis
    environment:
      - REDIS_HOST=histories-redis
      - REDIS_PORT=6379
    build:
      context: ./histories
    image: superheatedboy/histories:latest
    ports:
      - "3005:3005"

  histories-redis:
    image: "redis:latest"
    container_name: histories-redis
    ports:
      - "6379:6379" #redis defalut port 6379
    volumes:
      - "./data/redis:/data"
      
  # reverse proxy for frontend using APIs
  nginx:
    depends_on:
      - customers
      - reviews
      - histories
      - histories-redis
      - reactfront
    restart: always
    build:
      context: ./nginxrp
    ports:
      - "3050:80"

# docker-compose up --build
# docker-compose exec reactfront sh
# docker-compose exec reactfront curl http://productsapi:3001/api/products


#全コンテナ停止: docker stop $(docker ps -q)
#全コンテナ削除: docker rm $(docker ps -q -a)
#全イメージ削除: docker rmi $(docker images -q)