 // https://qiita.com/kawasukeeee/items/7bc5d948e3029c8a3a23

POST https://httpbin.org/post HTTP/1.1
content-type: application/json

{
    "name": "ProtoOut Studio",
    "category": "school",
    "message": "ProtoOut Studioは日本初のプロトタイピング専門スクールです。"
}

###

GET https://httpbin.org/


###
// commerceJs

GET http://localhost:3003/api/reviews/prod_4OANwRbgawvYL8



//https://commercejs.com/docs/api/#list-all-categories

###
curl -X GET \
    -G "https://api.chec.io/v1/products?limit=25" \
    -H "X-Authorization: pk_test_399804b273a47b61d2895cb718d628c00954d012207ae" | jq .

curl -X GET \
    -G "https://api.chec.io/v1/products?sortBy=price&sortDirection=asc" \
    -H "X-Authorization: pk_test_399804b273a47b61d2895cb718d628c00954d012207ae" | jq .


curl -X GET \
    -G "https://api.chec.io/v1/carts" \
    -H "X-Authorization: pk_test_399804b273a47b61d2895cb718d628c00954d012207ae"


curl -X POST \
    "https://api.chec.io/v1/carts/cart_2Jwr9yJAeN4VlP" \
    -H "X-Authorization: pk_test_399804b273a47b61d2895cb718d628c00954d012207ae" \
    -H "Content-Type: application/json" \
    -d '{"id":"prod_R4OANwRqklvYL8","quantity":5}'


curl -X GET \
    -G "https://api.chec.io/v1/categories?depth=2" \
    -H "X-Authorization: pk_test_399804b273a47b61d2895cb718d628c00954d012207ae"



// create customer
curl -X POST \
    "https://api.chec.io/v1/customers" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" \
    -H "Content-Type: application/json" \
    -d '{"email":"leslie.lawless@example.com","phone":"+1 987 654 3210","firstname":"Leslie","lastname":"Lawless","external_id":"MY_CRM_USER_123"}'


###
// commerce js customer
// list customer
curl -X GET \
    -G "https://api.chec.io/v1/customers" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" | jq .


// create customer
curl -X POST \
    "https://api.chec.io/v1/customers" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" \
    -H "Content-Type: application/json" \
    -d '{"email":"leslie.lawless@example.com","phone":"+1 987 654 3210","firstname":"Leslie","lastname":"Lawless","external_id":"MY_CRM_USER_123"}'

curl -X POST \
    "https://api.chec.io/v1/customers" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" \
    -H "Content-Type: application/json" \
    -d '{"email":"satoaikawa@qq.com","phone":"+1 987 654 3210","firstname":"Leslie","lastname":"Lawless","external_id":"MY_CRM_USER_123"}'




// list orders
curl -X GET \
    -G "https://api.chec.io/v1/customers/cstmr_0YnEoqP8Zmwe7P/orders" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" | jq .


// get jwt for cutomer
curl -X POST \
    "https://api.chec.io/v1/customers/cstmr_zkK6oL9PaR5Xn0/issue-token" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba"


###

// Issue and send login token W/O customerId
// Issue and send login token, customer's email and base_url(jumping) needed
curl -X POST \
    "https://api.chec.io/v1/customers/email-token" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" \
    -H "Content-Type: application/json" \
    -d '{"email":"satoaikawa@qq.com","base_url":"http://localhost:3000/registration-success"}'

// response
// http://localhost:3000/registration-success/fa4258c2-b34c-480e-b6cb-2df2a7718f6a
// Exchange login token for JWT W/O customerId
curl -X POST \
    "https://api.chec.io/v1/customers/exchange-token" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" \
    -H "Content-Type: application/json" \
    -d '{"token":"fa4258c2-b34c-480e-b6cb-2df2a7718f6a"}'

// response contains customerID and jwt
//{
//    "customer_id": "cstmr_zkK6oL9PaR5Xn0",
//    "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5jaGVjLmlvIiwiaWF0IjoxNjQ2MDUzNzg5LjcyMDI0LCJuYmYiOjE2NDYwNTM3ODkuNzIwMjY5LCJleHAiOjE2NDYxNDAxODkuNzIwMjc3LCJjaWQiOiJjc3Rtcl96a0s2b0w5UGFSNVhuMCJ9.Cn_ldDq9zCbEQN8ZkO6c0cKTu5vI493il5ymXnRV-Vg"
//}


// list order for customer
curl -X GET \
    -G "https://api.chec.io/v1/customers/cstmr_0YnEoqP8Zmwe7P/orders" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba"



curl -X GET \
    -G "https://api.chec.io/v1/customers/cstmr_zkK6oL9PaR5Xn0/orders" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba"


curl -X POST \
    "https://api.chec.io/v1/customers" \
    -H "X-Authorization: sk_test_39980259115a0d9753812433d6740aa60b83dc9a64fba" \
    -H "Content-Type: application/json" \
    -d '{"email":"satoaikawa@qq.com","phone":"+1 987 654 3210","firstname":"Leslie","lastname":"Lawless","external_id":"MY_CRM_USER_123"}'



###

POST http://localhost:3002/api/login HTTP/1.1
content-type: application/json

{
    "email": "satoaikawa@qq.com",
    "password": "test"
}

###
POST http://localhost:3002/api/register HTTP/1.1
content-type: application/json

{
    "customer_id": "customer_test_2_abc",
    "firstname": "satoshi",
    "lastname": "aikawa",
    "email": "sasa@qq.com",
    "password": "test"
}