 // https://qiita.com/kawasukeeee/items/7bc5d948e3029c8a3a23

POST https://httpbin.org/post HTTP/1.1
content-type: application/json

{
    "name": "ProtoOut Studio",
    "category": "school",
    "message": "ProtoOut Studioは日本初のプロトタイピング専門スクールです。"
}

###

GET https://httpbin.org/


###
// commerceJs
GET http://localhost:3002/login HTTP/1.1
###
POST http://localhost:3002/loginn HTTP/1.1


{
    "email": "Hyman.Wisozk@example.com",
    "password": "Alfred34Hyman.Wisozk@example.com"
}

// curl -X POST http://localhost:3002/loginn -H "Accept: application/json" -H "Content-type: application/json" -d '{ "email": "Hyman.Wisozk@example.com", "password": "Alfred34Hyman.Wisozk@example.com" }'